# Generated by Django 3.0.7 on 2021-10-24 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20211024_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scrap',
            field=models.ManyToManyField(blank=True, related_name='scrap_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
